version: "3"

services:
  # =============== NODE 0 ===================
  iroha_node_0:
    image: hyperledger/iroha:latest
    container_name: iroha_node_0
    expose:
      - 10001
    ports:
      - 50051:50051
    environment:
      - "KEY=node0"
      - "IROHA_POSTGRES_HOST=postgres_0"
    volumes:
      - ./data/blockstore0:/tmp/block_store
      - ./config0:/opt/iroha_data
    depends_on:
      - postgres_0
    restart: always
  
  postgres_0:
    image: postgres:9.5
    container_name: postgres_0
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    restart: always
  
  # =============== NODE 1 ===================
  iroha_node_1:
    image: hyperledger/iroha:latest
    container_name: iroha_node_1
    expose:
      - 10001
    ports:
      - 50052:50051
    environment:
      - "KEY=node1"
      - "IROHA_POSTGRES_HOST=postgres_1"
    volumes:
      - ./data/blockstore1:/tmp/block_store
      - ./config1:/opt/iroha_data
    depends_on:
      - postgres_1
    restart: always
  
  postgres_1:
    image: postgres:9.5
    container_name: postgres_1
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5433:5432
    restart: always

  # =============== NODE 2 ===================
  iroha_node_2:
    image: hyperledger/iroha:latest
    container_name: iroha_node_2
    expose:
      - 10001
    ports:
      - 50053:50051
    environment:
      - "KEY=node2"
      - "IROHA_POSTGRES_HOST=postgres_2"
    volumes:
      - ./data/blockstore2:/tmp/block_store
      - ./config2:/opt/iroha_data
    depends_on:
      - postgres_2
    restart: always
  
  postgres_2:
    image: postgres:9.5
    container_name: postgres_2
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5434:5432
    restart: always

  # =============== NODE 3 ===================
  iroha_node_3:
    image: hyperledger/iroha:latest
    container_name: iroha_node_3
    expose:
      - 10001
    ports:
      - 50054:50051
    environment:
      - "KEY=node3"
      - "IROHA_POSTGRES_HOST=postgres_3"
    volumes:
      - ./data/blockstore3:/tmp/block_store
      - ./config3:/opt/iroha_data
    depends_on:
      - postgres_3
    restart: always
  
  postgres_3:
    image: postgres:9.5
    container_name: postgres_3
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5435:5432
    restart: always